# Generated by Django 5.2.17 on 2026-09-30 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reseau", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("total_ht", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_tva", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_ttc", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "vendeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vente",
                "ordering": ["-cree_le"],
                "permissions": [("appliquer_remise", "Peut appliquer une remise")],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("carte", "Carte bancaire"),
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="ventes.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                ("quantite", models.PositiveIntegerField()),
                (
                    "prix_unitaire_ttc",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "remise_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("taux_tva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_ttc", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="ventes.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de vente",
            },
        ),
        migrations.CreateModel(
            name="CompteurFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField()),
                ("dernier", models.PositiveIntegerField(default=0)),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "compteur de factures",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("magasin", "annee"), name="compteur_unique_par_annee"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vente",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"), name="facture_sans_doublon"
            ),
        ),
    ]
