# Generated by Django 5.2.17 on 2026-10-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0010_droits_avoirs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compteurfacture",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("ticket", "Ticket de caisse"),
                    ("facture", "Facture"),
                    ("devis", "Devis"),
                    ("avoir", "Avoir"),
                    ("achat", "Commande fournisseur"),
                ],
                max_length=10,
            ),
        ),
    ]
