# Generated by Django 5.2.17 on 2026-10-02 14:46

from django.db import migrations, models


def copier_le_client(apps, schema_editor):
    Facture = apps.get_model("ventes", "Facture")
    for facture in Facture.objects.select_related("client"):
        client = facture.client
        ville = " ".join(filter(None, [client.code_postal, client.ville]))
        facture.client_nom = client.societe or f"{client.nom.upper()} {client.prenom}"
        facture.client_adresse = ", ".join(filter(None, [client.adresse, ville]))
        facture.client_matricule_fiscal = client.matricule_fiscal
        facture.save(update_fields=["client_nom", "client_adresse", "client_matricule_fiscal"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_fiche_client_complete"),
        ("ventes", "0011_type_commande_fournisseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="client_adresse",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="facture",
            name="client_matricule_fiscal",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="facture",
            name="client_nom",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(copier_le_client, migrations.RunPython.noop),
    ]
