# Generated by Django 5.2.17 on 2026-10-02 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_fiche_client_complete"),
        ("reseau", "0003_peniches"),
        ("ventes", "0012_facture_copie_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="peniche",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Bac où l'équipement de la commande attend sa livraison ; libre après.",
                null=True,
                verbose_name="péniche",
            ),
        ),
        migrations.AddConstraint(
            model_name="vente",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("peniche__isnull", False), ("statut", "en_commande")
                ),
                fields=("magasin", "peniche"),
                name="une_commande_par_peniche",
            ),
        ),
    ]
