# Generated by Django 5.2.17 on 2026-10-03 19:42

from django.db import migrations

from apps.securite.roles import PERMISSIONS_PILOTAGE, ajouter_aux_roles_existants


def ajouter(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_PILOTAGE)


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0013_peniche_des_commandes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vente",
            options={
                "ordering": ["-cree_le"],
                "permissions": [
                    ("appliquer_remise", "Peut appliquer une remise"),
                    ("consulter_reporting", "Peut consulter le reporting des ventes"),
                ],
                "verbose_name": "vente",
            },
        ),
        migrations.RunPython(ajouter, migrations.RunPython.noop),
    ]
