# Generated by Django 5.2.17 on 2026-10-04 00:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core import rls


# Les étapes suivent leur vente (la sous-requête est elle-même filtrée).
CONDITION = "EXISTS (SELECT 1 FROM ventes_vente v WHERE v.id = vente_id)"


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.activer("ventes_etapecommande", CONDITION))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.desactiver("ventes_etapecommande"))


class Migration(migrations.Migration):
    dependencies = [
        ("ventes", "0014_droit_reporting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="etape",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a_commander", "Visite créée à commander"),
                    ("commandee", "Commandée, en attente de réception BL"),
                    ("montage", "Montage en cours"),
                    ("controle", "Contrôle qualité"),
                    ("contact_client", "Client prévenu"),
                    ("instance", "En instance"),
                ],
                help_text="Dernière étape saisie au suivi ; vide, l'étape vient des verres commandés.",
                max_length=16,
                verbose_name="étape de l'atelier",
            ),
        ),
        migrations.CreateModel(
            name="EtapeCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etape",
                    models.CharField(
                        choices=[
                            ("a_commander", "Visite créée à commander"),
                            ("commandee", "Commandée, en attente de réception BL"),
                            ("montage", "Montage en cours"),
                            ("controle", "Contrôle qualité"),
                            ("contact_client", "Client prévenu"),
                            ("instance", "En instance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("observation", models.CharField(blank=True, max_length=300)),
                ("le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etapes",
                        to="ventes.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "étape de commande",
                "verbose_name_plural": "étapes de commande",
                "ordering": ["le", "pk"],
            },
        ),
        migrations.RunPython(cloisonner, decloisonner),
    ]
