# Generated by Django 5.2.17 on 2026-10-04 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_PRISES_EN_CHARGE, ajouter_aux_roles_existants
from core import rls


# Les prises en charge suivent leur vente (la sous-requête est elle-même filtrée).
CONDITION = "EXISTS (SELECT 1 FROM ventes_vente v WHERE v.id = vente_id)"


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.activer("ventes_priseencharge", CONDITION))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.desactiver("ventes_priseencharge"))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_PRISES_EN_CHARGE)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_prise_en_charge"),
        ("ventes", "0015_suivi_commandes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriseEnCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("montant", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "numero_dossier",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="n° de dossier"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demandee", "Demandée"),
                            ("accordee", "Accordée"),
                            ("reglee", "Réglée par l'organisme"),
                            ("refusee", "Refusée"),
                        ],
                        default="demandee",
                        max_length=10,
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="crm.organisme",
                    ),
                ),
                (
                    "saisie_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prises_en_charge",
                        to="ventes.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "prise en charge",
                "verbose_name_plural": "prises en charge",
                "ordering": ["cree_le"],
            },
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
