# Generated by Django 5.2.17 on 2026-10-04 16:47

import django.db.models.deletion
from django.db import migrations, models

from core import rls

# Les lunettes suivent leur vente (la sous-requête est elle-même filtrée).
CONDITION = "EXISTS (SELECT 1 FROM ventes_vente v WHERE v.id = vente_id)"


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.activer("ventes_lunette", CONDITION))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.desactiver("ventes_lunette"))


class Migration(migrations.Migration):

    dependencies = [
        ("optique", "0003_identifiant_prescripteur"),
        ("ventes", "0016_prises_en_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignevente",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monture", "Monture"),
                    ("verre_d", "Verre droit"),
                    ("verre_g", "Verre gauche"),
                    ("supplement_d", "Supplément verre droit"),
                    ("supplement_g", "Supplément verre gauche"),
                ],
                help_text="Place dans la lunette.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Lunette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        help_text="N° de la lunette dans la visite (1, 2…)."
                    ),
                ),
                (
                    "vision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("loin", "Loin"),
                            ("pres", "Près"),
                            ("double_foyer", "Double foyer"),
                            ("degressif", "Dégressif"),
                            ("progressif", "Progressif"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "solaire",
                    models.BooleanField(
                        default=False, help_text="Lunette solaire (sinon optique)."
                    ),
                ),
                (
                    "inadaptation",
                    models.BooleanField(
                        default=False,
                        help_text="Refaite parce que le client ne s'est pas adapté.",
                    ),
                ),
                (
                    "oeil_directeur",
                    models.CharField(
                        blank=True,
                        choices=[("droit", "Droit"), ("gauche", "Gauche")],
                        max_length=10,
                    ),
                ),
                (
                    "ecart_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Demi-écart pupillaire de loin, œil droit (mm).",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "ecart_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Demi-écart pupillaire de loin, œil gauche (mm).",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "ecart_pres_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Demi-écart de près, œil droit (mm).",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "ecart_pres_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Demi-écart de près, œil gauche (mm).",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "hauteur_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hauteur de montage, œil droit (mm).",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "hauteur_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hauteur de montage, œil gauche (mm).",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "client_absent",
                    models.BooleanField(
                        default=False,
                        help_text="Mesures prises sans le client (reprise d'une ancienne lunette).",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ordonnance d'où vient la correction ; vide pour une solaire sans correction.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lunettes",
                        to="optique.prescription",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lunettes",
                        to="ventes.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "lunette",
                "ordering": ["vente", "numero"],
            },
        ),
        migrations.AddField(
            model_name="lignevente",
            name="lunette",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes",
                to="ventes.lunette",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunette",
            constraint=models.UniqueConstraint(
                fields=("vente", "numero"), name="lunette_numero_unique"
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
    ]
