# Generated by Django 5.2.17 on 2026-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0019_factures_achat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compteurfacture",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("ticket", "Ticket de caisse"),
                    ("facture", "Facture"),
                    ("devis", "Devis"),
                    ("avoir", "Avoir"),
                    ("achat", "Commande fournisseur"),
                    ("reception", "Bon de réception"),
                    ("fac_achat", "Facture achat"),
                    ("bon_retour", "Bon retour fournisseur"),
                    ("transfert", "Transfert de stock"),
                ],
                max_length=10,
            ),
        ),
    ]
