# Generated by Django 5.2.17 on 2026-10-09 17:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_BORDEREAUX, PERMISSIONS_SAV, ajouter_aux_roles_existants
from core import rls

TABLES = {
    "ventes_bordereaupec": "optilink_magasin_visible(magasin_id)",
    "ventes_dossiersav": "optilink_magasin_visible(magasin_id)",
    # Les étapes suivent leur dossier (la sous-requête est elle-même filtrée).
    "ventes_evenementsav": "EXISTS (SELECT 1 FROM ventes_dossiersav d WHERE d.id = dossier_id)",
}


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    for permissions in (PERMISSIONS_BORDEREAUX, PERMISSIONS_SAV):
        ajouter_aux_roles_existants(apps, permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0007_bonretour_ligneretour_and_more"),
        ("crm", "0008_organisme_convention"),
        ("reseau", "0008_banques"),
        ("stock", "0014_referentiels_verres"),
        ("ventes", "0021_inventaires"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="priseencharge",
            name="montant_regle",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Ce que l'organisme a payé ; l'écart avec le montant revient au client.",
                max_digits=14,
                null=True,
                verbose_name="montant réglé",
            ),
        ),
        migrations.AddField(
            model_name="priseencharge",
            name="motif_rejet",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="motif du rejet"
            ),
        ),
        migrations.AlterField(
            model_name="compteurfacture",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("ticket", "Ticket de caisse"),
                    ("facture", "Facture"),
                    ("devis", "Devis"),
                    ("avoir", "Avoir"),
                    ("achat", "Commande fournisseur"),
                    ("reception", "Bon de réception"),
                    ("fac_achat", "Facture achat"),
                    ("bon_retour", "Bon retour fournisseur"),
                    ("transfert", "Transfert de stock"),
                    ("inventaire", "Inventaire"),
                    ("sav", "Dossier SAV"),
                    ("bord_pec", "Bordereau de prise en charge"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BordereauPec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("preparation", "En préparation"),
                            ("envoye", "Envoyé"),
                            ("regle", "Réglé"),
                        ],
                        default="preparation",
                        max_length=12,
                    ),
                ),
                (
                    "envoye_le",
                    models.DateField(blank=True, null=True, verbose_name="envoyé le"),
                ),
                (
                    "regle_le",
                    models.DateField(blank=True, null=True, verbose_name="réglé le"),
                ),
                (
                    "mode_reglement",
                    models.CharField(
                        blank=True,
                        choices=[("virement", "Virement"), ("cheque", "Chèque")],
                        max_length=10,
                        verbose_name="mode de règlement",
                    ),
                ),
                (
                    "reference_reglement",
                    models.CharField(
                        blank=True,
                        help_text="N° de chèque ou de virement.",
                        max_length=60,
                        verbose_name="référence du règlement",
                    ),
                ),
                ("observation", models.CharField(blank=True, max_length=300)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="crm.organisme",
                    ),
                ),
            ],
            options={
                "verbose_name": "bordereau de prise en charge",
                "verbose_name_plural": "bordereaux de prise en charge",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.AddField(
            model_name="priseencharge",
            name="bordereau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prises_en_charge",
                to="ventes.bordereaupec",
            ),
        ),
        migrations.CreateModel(
            name="DossierSav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "designation",
                    models.CharField(
                        help_text="Ce que le client rapporte.",
                        max_length=200,
                        verbose_name="désignation",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("casse", "Casse"),
                            ("reglage", "Réglage, ajustage"),
                            ("defaut", "Défaut de fabrication"),
                            ("adaptation", "Non-adaptation aux verres"),
                            ("autre", "Autre"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Le problème constaté."),
                ),
                ("sous_garantie", models.BooleanField(default=False)),
                (
                    "etape",
                    models.CharField(
                        choices=[
                            ("recu", "Reçu au magasin"),
                            ("atelier", "En réparation à l'atelier"),
                            ("fournisseur", "Envoyé au fournisseur"),
                            ("pret", "Prêt à rendre"),
                            ("rendu", "Rendu au client"),
                            ("annule", "Annulé"),
                        ],
                        default="recu",
                        max_length=12,
                    ),
                ),
                (
                    "retour_prevu_le",
                    models.DateField(
                        blank=True, null=True, verbose_name="retour prévu le"
                    ),
                ),
                (
                    "solution",
                    models.CharField(
                        blank=True, help_text="Ce qui a été fait.", max_length=300
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers_sav",
                        to="crm.client",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="achats.fournisseur",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Visite ou vente d'origine de l'article.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers_sav",
                        to="ventes.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "dossier SAV",
                "verbose_name_plural": "dossiers SAV",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="EvenementSav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etape",
                    models.CharField(
                        choices=[
                            ("recu", "Reçu au magasin"),
                            ("atelier", "En réparation à l'atelier"),
                            ("fournisseur", "Envoyé au fournisseur"),
                            ("pret", "Prêt à rendre"),
                            ("rendu", "Rendu au client"),
                            ("annule", "Annulé"),
                        ],
                        max_length=12,
                    ),
                ),
                ("commentaire", models.CharField(blank=True, max_length=300)),
                ("le", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="ventes.dossiersav",
                    ),
                ),
                (
                    "par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "étape SAV",
                "verbose_name_plural": "étapes SAV",
                "ordering": ["le", "pk"],
            },
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
