# Generated by Django 5.2.17 on 2026-10-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_CREDIT_IMPAYES, ajouter_aux_roles_existants


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_CREDIT_IMPAYES)


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0023_type_reglement_fournisseur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vente",
            options={
                "ordering": ["-cree_le"],
                "permissions": [
                    ("appliquer_remise", "Peut appliquer une remise"),
                    ("consulter_reporting", "Peut consulter le reporting des ventes"),
                    (
                        "vendre_a_credit",
                        "Peut vendre à crédit (remettre sans que le client ait soldé)",
                    ),
                    (
                        "gerer_impayes",
                        "Peut gérer les impayés, les changements de chèque et la liste noire",
                    ),
                ],
                "verbose_name": "vente",
            },
        ),
        migrations.AddField(
            model_name="paiement",
            name="banque",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paiement",
            name="echeance",
            field=models.DateField(
                blank=True,
                help_text="Chèque ou traite : à remettre à la banque le.",
                null=True,
                verbose_name="échéance",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="impaye_le",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="motif_impaye",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="motif de l'impayé"
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="N° du chèque, de la traite ou du virement.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="remplace_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Changement de chèque : le règlement qui a pris sa place.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="remplace",
                to="ventes.paiement",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("encaisse", "Encaissé"),
                    ("impaye", "Impayé"),
                    ("remplace", "Remplacé"),
                ],
                default="encaisse",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="credit_accorde_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="credit_echeance",
            field=models.DateField(
                blank=True,
                help_text="Date promise par le client.",
                null=True,
                verbose_name="crédit à régler le",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="mode",
            field=models.CharField(
                choices=[
                    ("carte", "Carte bancaire"),
                    ("especes", "Espèces"),
                    ("cheque", "Chèque"),
                    ("virement", "Virement"),
                    ("traite", "Traite"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
