# Generated by Django 5.2.17 on 2026-10-09 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_FACTURATION_GROUPEE, ajouter_aux_roles_existants
from core import rls

TABLES = ("ventes_facturegroupee", "ventes_cloturemois")


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.activer(table, "optilink_magasin_visible(magasin_id)"))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_FACTURATION_GROUPEE)


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0009_liste_noire"),
        ("reseau", "0008_banques"),
        ("ventes", "0024_credit_impayes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactureGroupee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("client", "Facture groupée"),
                            ("mensuelle", "Facture récapitulative du mois"),
                        ],
                        default="client",
                        max_length=10,
                    ),
                ),
                ("client_nom", models.CharField(blank=True, max_length=200)),
                ("client_adresse", models.CharField(blank=True, max_length=320)),
                (
                    "client_matricule_fiscal",
                    models.CharField(blank=True, max_length=30),
                ),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("du", models.DateField(help_text="Première vente facturée.")),
                ("au", models.DateField(help_text="Dernière vente facturée.")),
                ("devise", models.CharField(max_length=3)),
                ("total_ht", models.DecimalField(decimal_places=3, max_digits=14)),
                ("total_tva", models.DecimalField(decimal_places=3, max_digits=14)),
                ("total_ttc", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "timbre_fiscal",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("net_a_payer", models.DecimalField(decimal_places=3, max_digits=14)),
                ("mode_paiement_timbre", models.CharField(blank=True, max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures_groupees",
                        to="crm.client",
                    ),
                ),
                (
                    "emise_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "facture groupée",
                "verbose_name_plural": "factures groupées",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="ClotureMois",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("mois", models.PositiveSmallIntegerField()),
                (
                    "cloture_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "facture",
                    models.OneToOneField(
                        blank=True,
                        help_text="Vide si toutes les ventes du mois étaient déjà facturées.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cloture",
                        to="ventes.facturegroupee",
                    ),
                ),
            ],
            options={
                "verbose_name": "clôture du mois",
                "verbose_name_plural": "clôtures des mois",
                "ordering": ["-annee", "-mois"],
            },
        ),
        migrations.AddField(
            model_name="avoir",
            name="facture_groupee",
            field=models.ForeignKey(
                blank=True,
                help_text="Facture groupée ou récapitulative corrigée.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avoirs",
                to="ventes.facturegroupee",
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="facture_groupee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventes",
                to="ventes.facturegroupee",
            ),
        ),
        migrations.AddConstraint(
            model_name="facturegroupee",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"),
                name="facture_groupee_sans_doublon",
            ),
        ),
        migrations.AddConstraint(
            model_name="cloturemois",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "mois"), name="un_mois_clos_une_fois"
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
