# Generated by Django 5.2.17 on 2026-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0025_facturation_groupee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compteurfacture",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("ticket", "Ticket de caisse"),
                    ("facture", "Facture"),
                    ("devis", "Devis"),
                    ("avoir", "Avoir"),
                    ("achat", "Commande fournisseur"),
                    ("reception", "Bon de réception"),
                    ("fac_achat", "Facture achat"),
                    ("bon_retour", "Bon retour fournisseur"),
                    ("transfert", "Transfert de stock"),
                    ("inventaire", "Inventaire"),
                    ("sav", "Dossier SAV"),
                    ("bord_pec", "Bordereau de prise en charge"),
                    ("reg_fourn", "Règlement fournisseur"),
                    ("bon_sortie", "Bon de sortie"),
                    ("dem_transf", "Demande de transfert"),
                ],
                max_length=10,
            ),
        ),
    ]
