# Generated by Django 5.2.17 on 2026-10-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "alerte",
                "verbose_name_plural": "alertes",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Reporting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "reporting des ventes",
                "verbose_name_plural": "reporting des ventes",
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
