# Generated by Django 5.2.17 on 2026-09-30 23:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reseau", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=40, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                (
                    "famille",
                    models.CharField(
                        choices=[
                            ("monture", "Monture"),
                            ("verre", "Verre"),
                            ("lentille", "Lentille"),
                            ("accessoire", "Accessoire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "code_barres",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "prix_vente_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "article",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        help_text="Positive en entrée, négative en sortie."
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reception", "Réception"),
                            ("vente", "Vente"),
                            ("retour", "Retour client"),
                            ("ajustement", "Ajustement d'inventaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="Pièce d'origine.", max_length=60
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="stock.article",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de stock",
                "verbose_name_plural": "mouvements de stock",
                "indexes": [
                    models.Index(
                        fields=["magasin", "article"],
                        name="stock_mouve_magasin_add381_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantite", 0), _negated=True),
                        name="mouvement_quantite_non_nulle",
                    )
                ],
            },
        ),
    ]
