# Generated by Django 5.2.17 on 2026-10-02 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def accessoires_en_divers(apps, schema_editor):
    apps.get_model("stock", "Article").objects.filter(famille="accessoire").update(
        famille="divers"
    )


def divers_en_accessoires(apps, schema_editor):
    apps.get_model("stock", "Article").objects.filter(famille="divers").update(
        famille="accessoire"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_article_sur_commande"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lentille",
            fields=[
                ("marque", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="lentille",
                        serialize=False,
                        to="stock.article",
                    ),
                ),
                (
                    "modele",
                    models.CharField(blank=True, max_length=100, verbose_name="modèle"),
                ),
                (
                    "renouvellement",
                    models.CharField(
                        choices=[
                            ("journaliere", "Journalière"),
                            ("bimensuelle", "Bimensuelle"),
                            ("mensuelle", "Mensuelle"),
                            ("trimestrielle", "Trimestrielle"),
                            ("annuelle", "Annuelle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("spherique", "Sphérique"),
                            ("torique", "Torique"),
                            ("multifocale", "Multifocale"),
                        ],
                        default="spherique",
                        max_length=20,
                    ),
                ),
                (
                    "rayon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Rayon de courbure (mm).",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "diametre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mm",
                        max_digits=3,
                        null=True,
                        verbose_name="diamètre",
                    ),
                ),
                (
                    "puissance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "cylindre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "axe",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(180)],
                    ),
                ),
                (
                    "addition",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "lentilles_par_boite",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "caractéristiques de la lentille",
                "verbose_name_plural": "caractéristiques des lentilles",
            },
        ),
        migrations.CreateModel(
            name="Monture",
            fields=[
                ("marque", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="monture",
                        serialize=False,
                        to="stock.article",
                    ),
                ),
                (
                    "modele",
                    models.CharField(blank=True, max_length=100, verbose_name="modèle"),
                ),
                ("couleur", models.CharField(blank=True, max_length=60)),
                (
                    "matiere",
                    models.CharField(blank=True, max_length=60, verbose_name="matière"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cerclee", "Cerclée"),
                            ("semi_cerclee", "Semi-cerclée (nylor)"),
                            ("percee", "Percée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("mixte", "Mixte"),
                            ("enfant", "Enfant"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "calibre",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="mm", null=True
                    ),
                ),
                (
                    "pont",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="mm", null=True
                    ),
                ),
                (
                    "branche",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="mm", null=True
                    ),
                ),
                ("solaire", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "caractéristiques de la monture",
                "verbose_name_plural": "caractéristiques des montures",
            },
        ),
        migrations.CreateModel(
            name="Verre",
            fields=[
                ("marque", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="verre",
                        serialize=False,
                        to="stock.article",
                    ),
                ),
                (
                    "gamme",
                    models.CharField(
                        blank=True, help_text="Nom commercial du verre.", max_length=100
                    ),
                ),
                (
                    "geometrie",
                    models.CharField(
                        choices=[
                            ("unifocal", "Unifocal"),
                            ("progressif", "Progressif"),
                            ("degressif", "Dégressif"),
                            ("bifocal", "Bifocal"),
                        ],
                        max_length=20,
                        verbose_name="géométrie",
                    ),
                ),
                (
                    "indice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="1.500, 1.600, 1.670…",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "matiere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("organique", "Organique"),
                            ("polycarbonate", "Polycarbonate"),
                            ("mineral", "Minéral"),
                        ],
                        max_length=20,
                        verbose_name="matière",
                    ),
                ),
                (
                    "traitements",
                    models.CharField(
                        blank=True,
                        help_text="Antireflet, durci, filtre lumière bleue…",
                        max_length=200,
                    ),
                ),
                ("photochromique", models.BooleanField(default=False)),
                ("teinte", models.CharField(blank=True, max_length=60)),
                (
                    "diametre",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="mm", null=True, verbose_name="diamètre"
                    ),
                ),
            ],
            options={
                "verbose_name": "caractéristiques du verre",
                "verbose_name_plural": "caractéristiques des verres",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="famille",
            field=models.CharField(
                choices=[
                    ("monture", "Monture"),
                    ("verre", "Verre"),
                    ("lentille", "Lentille"),
                    ("divers", "Divers"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(accessoires_en_divers, divers_en_accessoires),
    ]
