# Generated by Django 5.2.17 on 2026-10-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0003_droits_des_roles"),
        ("stock", "0005_familles_d_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="achats.fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reference_fournisseur",
            field=models.CharField(
                blank=True,
                help_text="Référence de l'article chez le fournisseur.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="sur_commande",
            field=models.BooleanField(
                default=False,
                help_text="Commandé au fournisseur pour chaque client (verre à commander) : hors stock du magasin. Décoché, l'article se vend sur le stock (verre de stock, monture…).",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code_barres", ""), _negated=True),
                fields=("code_barres",),
                name="code_barres_unique",
                violation_error_message="Ce code-barres est déjà celui d'un autre article.",
            ),
        ),
    ]
