# Generated by Django 5.2.17 on 2026-10-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0003_droits_des_roles"),
        ("stock", "0006_fournisseur_et_code_barres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="fournisseur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="achats.fournisseur",
            ),
        ),
    ]
