# Generated by Django 5.2.17 on 2026-10-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0007_fournisseur_obligatoire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="famille",
            field=models.CharField(
                choices=[
                    ("monture", "Monture"),
                    ("verre", "Verre"),
                    ("lentille", "Lentille"),
                    ("divers", "Divers"),
                    ("supplement", "Supplément verre"),
                ],
                max_length=20,
            ),
        ),
    ]
