# Generated by Django 5.2.17 on 2026-10-05 13:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
import unicodedata

from django.db import migrations, models


MATIERES = {
    "acetate": "acetate",
    "titane": "titane",
    "titanium": "titane",
    "acier": "acier",
    "inox": "acier",
    "tr90": "tr90",
    "corne": "corne",
    "bois": "bois",
    "metal": "metal",
}


def _cle(texte):
    texte = unicodedata.normalize("NFKD", texte or "").encode("ascii", "ignore").decode()
    return "".join(texte.lower().split()).replace("-", "")


def reprendre(apps, schema_editor):
    """Famille d'après l'ancienne case « solaire » ; matières connues mises en liste."""
    Monture = apps.get_model("stock", "Monture")
    Monture.objects.filter(solaire=True).update(categorie="solaire")
    for fiche in Monture.objects.exclude(matiere=""):
        connue = MATIERES.get(_cle(fiche.matiere))
        if connue and connue != fiche.matiere:
            fiche.matiere = connue
            fiche.save(update_fields=["matiere"])


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0008_famille_supplement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="etui_special",
            field=models.BooleanField(default=False, verbose_name="étui spécial"),
        ),
        migrations.AddField(
            model_name="article",
            name="fodec",
            field=models.BooleanField(
                default=False,
                help_text="Achat soumis au FODEC (1 % du net HT).",
                verbose_name="FODEC",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="observation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="promotion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="suivi_numero_serie",
            field=models.BooleanField(
                default=False,
                help_text="Chaque pièce a son numéro de série.",
                verbose_name="numéro de série",
            ),
        ),
        migrations.AddField(
            model_name="monture",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("optique", "Lunette Optique"),
                    ("solaire", "Lunette Solaire"),
                    ("applique", "Lunette Applique"),
                ],
                default="optique",
                max_length=10,
                verbose_name="famille",
            ),
        ),
        migrations.AddField(
            model_name="monture",
            name="couleur_verres",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="monture",
            name="forme",
            field=models.CharField(
                blank=True, help_text="Ronde, rectangle, papillon…", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="monture",
            name="tranche_age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adulte", "Adulte"),
                    ("junior", "Junior"),
                    ("enfant", "Enfant"),
                    ("bebe", "Bébé"),
                ],
                max_length=10,
                verbose_name="tranche d'âge",
            ),
        ),
        migrations.AddField(
            model_name="prixarticle",
            name="prix_achat_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Prix d'achat brut, avant remise.",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="prix d'achat HT",
            ),
        ),
        migrations.AddField(
            model_name="prixarticle",
            name="taux_remise_achat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="remise à l'achat (%)",
            ),
        ),
        migrations.AlterField(
            model_name="monture",
            name="calibre",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Taille du verre, mm.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="monture",
            name="couleur",
            field=models.CharField(blank=True, max_length=60, verbose_name="couleur monture"),
        ),
        migrations.AlterField(
            model_name="monture",
            name="matiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("acetate", "Acétate"),
                    ("titane", "Titane"),
                    ("acier", "Acier"),
                    ("tr90", "TR90"),
                    ("corne", "Corne"),
                    ("bois", "Bois"),
                    ("metal", "Métal"),
                ],
                max_length=60,
                verbose_name="matière",
            ),
        ),
        migrations.AlterField(
            model_name="monture",
            name="solaire",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="verre",
            name="matiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organique", "Organique"),
                    ("polycarbonate", "Polycarbonate"),
                    ("mineral", "Minéral"),
                ],
                max_length=60,
                verbose_name="matière",
            ),
        ),
        migrations.RunPython(reprendre, migrations.RunPython.noop),
    ]
