# Generated by Django 5.2.17 on 2026-10-05 19:53

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_TRANSFERTS, ajouter_aux_roles_existants
from core import rls

# Un transfert est visible du magasin de départ et du magasin destinataire.
TABLES = {
    "stock_transfertstock": "optilink_magasin_visible(magasin_id) "
    "OR optilink_magasin_visible(destination_id)",
    "stock_lignetransfert": "EXISTS (SELECT 1 FROM stock_transfertstock t WHERE t.id = transfert_id)",
}
PERMS = PERMISSIONS_TRANSFERTS


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMS)



class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0006_magasin_type"),
        ("stock", "0009_fiche_monture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementstock",
            name="type",
            field=models.CharField(
                choices=[
                    ("reception", "Réception"),
                    ("vente", "Vente"),
                    ("retour", "Retour client"),
                    ("ajustement", "Ajustement d'inventaire"),
                    ("retour_fournisseur", "Retour au fournisseur"),
                    ("transfert_sortie", "Transfert envoyé"),
                    ("transfert_entree", "Transfert reçu"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TransfertStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("envoye", "Envoyé (en route)"), ("recu", "Reçu")],
                        default="envoye",
                        max_length=10,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("recu_le", models.DateTimeField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                        verbose_name="magasin destinataire",
                    ),
                ),
                (
                    "envoye_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                        verbose_name="magasin de départ",
                    ),
                ),
                (
                    "recu_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "transfert de stock",
                "verbose_name_plural": "transferts de stock",
                "ordering": ["-annee", "-sequence"],
            },
        ),
        migrations.CreateModel(
            name="LigneTransfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="quantité")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "transfert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.transfertstock",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de transfert",
                "verbose_name_plural": "lignes de transfert",
            },
        ),
        migrations.AddConstraint(
            model_name="transfertstock",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"), name="transfert_sans_doublon"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfertstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("destination", models.F("magasin")), _negated=True),
                name="transfert_vers_un_autre_magasin",
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
