# Generated by Django 5.2.17 on 2026-10-05 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_INVENTAIRES, ajouter_aux_roles_existants
from core import rls

TABLES = {
    "stock_inventaire": "optilink_magasin_visible(magasin_id)",
    "stock_ligneinventaire": "EXISTS (SELECT 1 FROM stock_inventaire i WHERE i.id = inventaire_id)",
}


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_INVENTAIRES)


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0007_bonretour_ligneretour_and_more"),
        ("reseau", "0006_magasin_type"),
        ("stock", "0010_alter_mouvementstock_type_transfertstock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "famille",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monture", "Monture"),
                            ("verre", "Verre"),
                            ("lentille", "Lentille"),
                            ("divers", "Divers"),
                            ("supplement", "Supplément verre"),
                        ],
                        help_text="Vide : tout le stock du magasin.",
                        max_length=20,
                    ),
                ),
                (
                    "marque",
                    models.CharField(
                        blank=True,
                        help_text="Montures de cette marque.",
                        max_length=100,
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optique", "Lunette Optique"),
                            ("solaire", "Lunette Solaire"),
                            ("applique", "Lunette Applique"),
                        ],
                        help_text="Montures optiques, solaires ou appliques.",
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours de comptage"),
                            ("valide", "Validé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_cours",
                        max_length=10,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("valide_le", models.DateTimeField(blank=True, null=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="achats.fournisseur",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "inventaire",
                "ordering": ["-annee", "-sequence"],
                "permissions": [
                    (
                        "valider_inventaire",
                        "Peut valider un inventaire (corrige le stock)",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LigneInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_comptee",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantité comptée"
                    ),
                ),
                (
                    "stock_theorique",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="stock de l'application"
                    ),
                ),
                ("ecart", models.IntegerField(blank=True, null=True)),
                ("observation", models.CharField(blank=True, max_length=200)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "inventaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.inventaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne d'inventaire",
                "verbose_name_plural": "lignes d'inventaire",
            },
        ),
        migrations.AddConstraint(
            model_name="inventaire",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"), name="inventaire_sans_doublon"
            ),
        ),
        migrations.AddConstraint(
            model_name="ligneinventaire",
            constraint=models.UniqueConstraint(
                fields=("inventaire", "article"), name="inventaire_article_unique"
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
