# Generated by Django 5.2.17 on 2026-10-05 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0011_inventaires"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transfertstock",
            name="annule_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transfertstock",
            name="annule_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transfertstock",
            name="statut",
            field=models.CharField(
                choices=[
                    ("envoye", "Envoyé (en route)"),
                    ("recu", "Reçu"),
                    ("annule", "Annulé"),
                ],
                default="envoye",
                max_length=10,
            ),
        ),
    ]
