# Generated by Django 5.2.17 on 2026-10-07 17:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0008_banques"),
        ("stock", "0012_transfert_annule"),
    ]

    operations = [
        migrations.AddField(
            model_name="verre",
            name="diametre_commercial",
            field=models.CharField(
                blank=True,
                help_text="65/70, 70/75…",
                max_length=20,
                verbose_name="diamètre commercial",
            ),
        ),
        migrations.AddField(
            model_name="verre",
            name="fabrication",
            field=models.CharField(
                choices=[
                    ("stock", "Verre de stock fournisseur"),
                    ("prescription", "Verre de prescription (RX, importation)"),
                ],
                default="prescription",
                help_text="Verre sur commande : pris dans le stock du fournisseur, ou fabriqué à la prescription. Un verre vendu sur le stock du magasin n'est pas sur commande.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlageVerre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=1)),
                (
                    "sphere_debut",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sphère la plus basse.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-40")),
                            django.core.validators.MaxValueValidator(Decimal("40")),
                        ],
                    ),
                ),
                (
                    "sphere_fin",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sphère la plus haute.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-40")),
                            django.core.validators.MaxValueValidator(Decimal("40")),
                        ],
                    ),
                ),
                (
                    "cylindre_debut",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cylindre le plus faible.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-40")),
                            django.core.validators.MaxValueValidator(Decimal("40")),
                        ],
                    ),
                ),
                (
                    "cylindre_fin",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cylindre le plus fort.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-40")),
                            django.core.validators.MaxValueValidator(Decimal("40")),
                        ],
                    ),
                ),
                (
                    "prix_achat_ht",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="prix d'achat HT",
                    ),
                ),
                (
                    "prix_vente_ttc",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plages",
                        to="stock.article",
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "plage de puissances",
                "verbose_name_plural": "plages de puissances et prix",
                "ordering": ["article", "ordre", "sphere_debut"],
            },
        ),
    ]
