# Generated by Django 5.2.17 on 2026-10-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0007_bonretour_ligneretour_and_more"),
        ("stock", "0013_plages_verres"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarqueMonture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "libelle",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="libellé"
                    ),
                ),
            ],
            options={
                "verbose_name": "marque de monture",
                "verbose_name_plural": "marques de monture",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="MatiereVerre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
            ],
            options={
                "verbose_name": "matière de verre",
                "verbose_name_plural": "matières de verre",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="CouleurVerre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
                (
                    "famille_couleur",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("blanc", "Blanc"),
                            ("solaire", "Solaire (teinté)"),
                            ("photochromique", "Photochromique"),
                            ("polarisant", "Polarisant"),
                            ("miroir", "Miroir"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="achats.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "couleur de verre",
                "verbose_name_plural": "couleurs de verre",
                "ordering": ["fournisseur__nom", "libelle"],
            },
        ),
        migrations.AddField(
            model_name="verre",
            name="couleur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verres",
                to="stock.couleurverre",
            ),
        ),
        migrations.CreateModel(
            name="DiametreVerre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "diametre_reel",
                    models.CharField(max_length=20, verbose_name="diamètre réel"),
                ),
                (
                    "diametre_commercial",
                    models.CharField(max_length=20, verbose_name="diamètre commercial"),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="achats.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "diamètre de verre",
                "verbose_name_plural": "diamètres de verre",
                "ordering": ["fournisseur__nom", "diametre_commercial"],
            },
        ),
        migrations.CreateModel(
            name="FamilleVerre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
                (
                    "foyer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unifocal", "Unifocal"),
                            ("bifocal", "Bifocal"),
                            ("progressif", "Progressif"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="achats.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "famille de verres",
                "verbose_name_plural": "familles de verres",
                "ordering": ["fournisseur__nom", "libelle"],
            },
        ),
        migrations.AddField(
            model_name="verre",
            name="famille_verre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verres",
                to="stock.familleverre",
            ),
        ),
        migrations.CreateModel(
            name="SousFamilleVerre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
                (
                    "foyer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unifocal", "Unifocal"),
                            ("bifocal", "Bifocal"),
                            ("progressif", "Progressif"),
                        ],
                        help_text="Vide : celui de la famille.",
                        max_length=20,
                    ),
                ),
                (
                    "famille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sous_familles",
                        to="stock.familleverre",
                    ),
                ),
            ],
            options={
                "verbose_name": "sous-famille de verres",
                "verbose_name_plural": "sous-familles de verres",
                "ordering": ["famille__libelle", "libelle"],
            },
        ),
        migrations.AddField(
            model_name="verre",
            name="sous_famille",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verres",
                to="stock.sousfamilleverre",
            ),
        ),
    ]
