# Generated by Django 5.2.17 on 2026-10-09 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_SORTIES_DEMANDES, ajouter_aux_roles_existants
from core import rls

# Une demande est visible du magasin demandeur et du magasin sollicité.
TABLES = {
    "stock_bonsortie": "optilink_magasin_visible(magasin_id)",
    "stock_lignesortie": "EXISTS (SELECT 1 FROM stock_bonsortie b WHERE b.id = bon_id)",
    "stock_demandetransfert": "optilink_magasin_visible(magasin_id) "
    "OR optilink_magasin_visible(aupres_de_id)",
    "stock_lignedemandetransfert": (
        "EXISTS (SELECT 1 FROM stock_demandetransfert d WHERE d.id = demande_id)"
    ),
}


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_SORTIES_DEMANDES)


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0008_banques"),
        ("stock", "0014_referentiels_verres"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementstock",
            name="type",
            field=models.CharField(
                choices=[
                    ("reception", "Réception"),
                    ("vente", "Vente"),
                    ("retour", "Retour client"),
                    ("ajustement", "Ajustement d'inventaire"),
                    ("retour_fournisseur", "Retour au fournisseur"),
                    ("transfert_sortie", "Transfert envoyé"),
                    ("transfert_entree", "Transfert reçu"),
                    ("sortie", "Bon de sortie"),
                    ("casse", "Sortie casse"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BonSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sortie", "Bon de sortie"),
                            ("casse", "Sortie casse"),
                        ],
                        default="sortie",
                        max_length=10,
                    ),
                ),
                ("motif", models.CharField(max_length=200)),
                ("observation", models.TextField(blank=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "bon de sortie",
                "verbose_name_plural": "bons de sortie",
                "ordering": ["-annee", "-sequence"],
            },
        ),
        migrations.CreateModel(
            name="DemandeTransfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("servie", "Servie"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("traitee_le", models.DateTimeField(blank=True, null=True)),
                ("motif_refus", models.CharField(blank=True, max_length=200)),
                (
                    "aupres_de",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                        verbose_name="magasin sollicité",
                    ),
                ),
                (
                    "demandee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                        verbose_name="magasin demandeur",
                    ),
                ),
                (
                    "traitee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfert",
                    models.OneToOneField(
                        blank=True,
                        help_text="Transfert qui a servi la demande.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demande",
                        to="stock.transfertstock",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de transfert",
                "verbose_name_plural": "demandes de transfert",
                "ordering": ["-annee", "-sequence"],
            },
        ),
        migrations.CreateModel(
            name="LigneDemandeTransfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(verbose_name="quantité demandée"),
                ),
                ("quantite_servie", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.demandetransfert",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de demande de transfert",
                "verbose_name_plural": "lignes de demande de transfert",
            },
        ),
        migrations.CreateModel(
            name="LigneSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="quantité")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "bon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.bonsortie",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de sortie",
                "verbose_name_plural": "lignes de sortie",
            },
        ),
        migrations.AddConstraint(
            model_name="bonsortie",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"), name="bon_sortie_sans_doublon"
            ),
        ),
        migrations.AddConstraint(
            model_name="demandetransfert",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"),
                name="demande_transfert_sans_doublon",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandetransfert",
            constraint=models.CheckConstraint(
                condition=models.Q(("aupres_de", models.F("magasin")), _negated=True),
                name="demande_a_un_autre_magasin",
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
