# Generated by Django 5.2.17 on 2026-10-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0015_sorties_demandes_transfert"),
    ]

    operations = [
        migrations.AddField(
            model_name="lentille",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("optique", "Lentille optique"),
                    ("solaire", "Lentille solaire"),
                ],
                default="optique",
                max_length=10,
                verbose_name="famille",
            ),
        ),
        migrations.AddField(
            model_name="lentille",
            name="couleur",
            field=models.CharField(
                blank=True,
                help_text="Couleur de la lentille ; vide si transparente.",
                max_length=60,
            ),
        ),
    ]
