# Generated by Django 5.2.17 on 2026-10-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0016_lentille_couleur_famille"),
    ]

    operations = [
        migrations.AddField(
            model_name="ligneinventaire",
            name="date_peremption",
            field=models.DateField(
                blank=True,
                help_text="Lentilles : date de péremption la plus proche des boîtes comptées.",
                null=True,
                verbose_name="péremption",
            ),
        ),
        migrations.AddField(
            model_name="lignetransfert",
            name="peremptions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lentilles : [{date, quantite}] des pièces envoyées (date vide : inconnue).",
                verbose_name="dates de péremption",
            ),
        ),
    ]
