# Generated by Django 5.2.17 on 2026-10-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0017_peremptions_lentilles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleLentille",
            fields=[],
            options={
                "verbose_name": "lentille",
                "verbose_name_plural": "lentilles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.article",),
        ),
        migrations.CreateModel(
            name="ArticleMonture",
            fields=[],
            options={
                "verbose_name": "monture",
                "verbose_name_plural": "montures",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.article",),
        ),
        migrations.CreateModel(
            name="ArticleProduit",
            fields=[],
            options={
                "verbose_name": "produit",
                "verbose_name_plural": "produits",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.article",),
        ),
        migrations.CreateModel(
            name="ArticleVerre",
            fields=[],
            options={
                "verbose_name": "verre",
                "verbose_name_plural": "verres",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.article",),
        ),
    ]
