# Generated by Django 5.2.17 on 2026-10-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0018_articles_par_famille"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouleurLentille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
            ],
            options={
                "verbose_name": "couleur de lentille",
                "verbose_name_plural": "couleurs de lentille",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="MarqueLentille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
            ],
            options={
                "verbose_name": "marque de lentille",
                "verbose_name_plural": "marques de lentille",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="MatiereLentille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code (repris de l'ancien logiciel).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("libelle", models.CharField(max_length=100, verbose_name="libellé")),
            ],
            options={
                "verbose_name": "matière de lentille",
                "verbose_name_plural": "matières de lentille",
                "ordering": ["libelle"],
            },
        ),
    ]
