# Generated by Django 5.2.17 on 2026-10-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _depot_de(apps):
    """{magasin_id: dépôt_id} : à la migration, chaque magasin a un seul dépôt."""
    Depot = apps.get_model("reseau", "Depot")
    depots = {}
    for depot in Depot.objects.order_by("-type", "code"):  # « vente » avant « central »
        depots.setdefault(depot.magasin_id, depot.pk)
    return depots


def remplir(apps, schema_editor):
    depots = _depot_de(apps)
    for nom in ("MouvementStock", "Inventaire", "BonSortie"):
        modele = apps.get_model("stock", nom)
        for magasin_id, depot_id in depots.items():
            modele.objects.filter(magasin_id=magasin_id).update(depot_id=depot_id)
    Transfert = apps.get_model("stock", "TransfertStock")
    for magasin_id, depot_id in depots.items():
        Transfert.objects.filter(magasin_id=magasin_id).update(depot_origine_id=depot_id)
        Transfert.objects.filter(destination_id=magasin_id).update(depot_destination_id=depot_id)


class Migration(migrations.Migration):
    dependencies = [
        ("reseau", "0009_depots"),
        ("stock", "0019_listes_lentilles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transfertstock",
            name="transfert_vers_un_autre_magasin",
        ),
        migrations.AddField(
            model_name="bonsortie",
            name="depot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="depot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="depot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
        migrations.AddField(
            model_name="transfertstock",
            name="depot_destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt destinataire",
            ),
        ),
        migrations.AddField(
            model_name="transfertstock",
            name="depot_origine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt de départ",
            ),
        ),
        migrations.AlterField(
            model_name="inventaire",
            name="famille",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monture", "Monture"),
                    ("verre", "Verre"),
                    ("lentille", "Lentille"),
                    ("divers", "Divers"),
                    ("supplement", "Supplément verre"),
                ],
                help_text="Vide : tout le stock du dépôt.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(fields=["depot", "article"], name="stock_mouve_depot_i_8b08de_idx"),
        ),
        migrations.AddConstraint(
            model_name="transfertstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("depot_destination", models.F("depot_origine")), _negated=True),
                name="transfert_vers_un_autre_depot",
            ),
        ),
        migrations.RunPython(remplir, migrations.RunPython.noop),
    ]
