# Generated by Django 5.2.17 on 2026-10-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reseau", "0009_depots"),
        ("stock", "0020_depots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonsortie",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
        migrations.AlterField(
            model_name="inventaire",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
        migrations.AlterField(
            model_name="transfertstock",
            name="depot_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt destinataire",
            ),
        ),
        migrations.AlterField(
            model_name="transfertstock",
            name="depot_origine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt de départ",
            ),
        ),
    ]
