# Generated by Django 5.2.17 on 2026-10-03 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reseau", "0005_societes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClotureCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                (
                    "debut",
                    models.DateTimeField(
                        blank=True, help_text="Vide pour la première.", null=True
                    ),
                ),
                ("fin", models.DateTimeField()),
                ("devise", models.CharField(max_length=3)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoyee", "Envoyée à la finance"),
                            ("validee", "Validée"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="envoyee",
                        max_length=10,
                    ),
                ),
                (
                    "fond_initial",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Fond laissé en caisse à la clôture précédente.",
                        max_digits=14,
                    ),
                ),
                (
                    "encaisse_especes",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "encaisse_cheques",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("nombre_cheques", models.PositiveIntegerField()),
                (
                    "encaisse_cartes",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "rembourse_especes",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "rembourse_cheques",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "rembourse_cartes",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("depenses", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "especes_comptees",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "cheques_comptes",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("nombre_cheques_comptes", models.PositiveIntegerField()),
                (
                    "cartes_comptees",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Total des tickets du terminal de paiement.",
                        max_digits=14,
                    ),
                ),
                (
                    "fond_conserve",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Espèces laissées en caisse pour le lendemain.",
                        max_digits=14,
                    ),
                ),
                ("commentaire_caissier", models.TextField(blank=True)),
                ("verifiee_le", models.DateTimeField(blank=True, null=True)),
                ("commentaire_finance", models.TextField(blank=True)),
                (
                    "cloturee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "verifiee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "clôture de caisse",
                "verbose_name_plural": "clôtures de caisse",
                "ordering": ["-fin"],
                "permissions": [
                    (
                        "valider_cloturecaisse",
                        "Peut valider ou rejeter une clôture de caisse",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DepenseCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("fournitures", "Fournitures"),
                            ("entretien", "Entretien et nettoyage"),
                            ("transport", "Transport et courses"),
                            ("restauration", "Restauration"),
                            ("divers", "Divers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motif", models.CharField(max_length=200)),
                (
                    "beneficiaire",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bénéficiaire"
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=3, max_digits=14)),
                ("payee_le", models.DateTimeField()),
                (
                    "cloture",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clôture qui l'a déduite ; vide tant que la caisse n'est pas clôturée.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depenses_caisse",
                        to="tresorerie.cloturecaisse",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "saisie_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dépense de caisse",
                "verbose_name_plural": "dépenses de caisse",
                "ordering": ["-payee_le"],
            },
        ),
    ]
