# Generated by Django 5.2.17 on 2026-10-03 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0005_societes"),
        ("tresorerie", "0003_droits_des_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cloturecaisse",
            name="alimentations",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Espèces ajoutées au fond de caisse pendant la période.",
                max_digits=14,
            ),
        ),
        migrations.CreateModel(
            name="CompteTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("banque", "Compte bancaire"),
                            ("coffre", "Coffre"),
                            ("caisse_centrale", "Caisse centrale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex. « BIAT agence Aouina », « Coffre T01 ».",
                        max_length=100,
                    ),
                ),
                ("banque", models.CharField(blank=True, max_length=100)),
                (
                    "rib",
                    models.CharField(blank=True, max_length=34, verbose_name="RIB"),
                ),
                ("devise", models.CharField(default="TND", max_length=3)),
                (
                    "solde_initial",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "magasin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pour un coffre : le magasin où il se trouve.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comptes",
                        to="reseau.societe",
                        verbose_name="société",
                    ),
                ),
            ],
            options={
                "verbose_name": "compte de trésorerie",
                "verbose_name_plural": "comptes de trésorerie",
                "ordering": ["societe", "type", "nom"],
            },
        ),
        migrations.CreateModel(
            name="OperationTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("depot_especes", "Dépôt des espèces des clôtures"),
                            ("depot_cheques", "Remise des chèques à la banque"),
                            (
                                "encaissement_cartes",
                                "Encaissement des cartes bancaires",
                            ),
                            ("transfert", "Transfert entre comptes"),
                            ("alimentation_fond", "Alimentation du fond de caisse"),
                            (
                                "operation_bancaire",
                                "Opération bancaire (frais, agios, autre)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("prevue", "Prévue"),
                            ("effectuee", "Effectuée"),
                            ("rapprochee", "Rapprochée avec la banque"),
                        ],
                        max_length=12,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "montant_credite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Cartes : montant réellement crédité par la banque (commission déduite).",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("date_prevue", models.DateField(blank=True, null=True)),
                ("date_operation", models.DateField(blank=True, null=True)),
                (
                    "date_valeur",
                    models.DateField(
                        blank=True, help_text="Date sur le relevé.", null=True
                    ),
                ),
                ("effectuee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="N° de bordereau ou de pièce bancaire.",
                        max_length=60,
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=200)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrees",
                        to="tresorerie.comptetresorerie",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Caisse alimentée, pour une alimentation du fond.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "rapprochee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.societe",
                        verbose_name="société",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorties",
                        to="tresorerie.comptetresorerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "opération de trésorerie",
                "verbose_name_plural": "opérations de trésorerie",
                "ordering": ["-cree_le"],
                "permissions": [
                    (
                        "rapprocher_operationtresorerie",
                        "Peut rapprocher une opération avec la banque",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="cloturecaisse",
            name="depot_cheques",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clotures_cheques",
                to="tresorerie.operationtresorerie",
            ),
        ),
        migrations.AddField(
            model_name="cloturecaisse",
            name="depot_especes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clotures_especes",
                to="tresorerie.operationtresorerie",
            ),
        ),
        migrations.AddField(
            model_name="cloturecaisse",
            name="encaissement_cartes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clotures_cartes",
                to="tresorerie.operationtresorerie",
            ),
        ),
    ]
