# Generated by Django 5.2.17 on 2026-10-03 15:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reseau", "0005_societes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "matricule",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("nom", models.CharField(max_length=80)),
                ("prenom", models.CharField(max_length=80, verbose_name="prénom")),
                (
                    "cin",
                    models.CharField(blank=True, max_length=20, verbose_name="CIN"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        help_text="Ex. opticien, vendeur, caissier.", max_length=80
                    ),
                ),
                ("date_embauche", models.DateField(verbose_name="date d'embauche")),
                ("date_sortie", models.DateField(blank=True, null=True)),
                (
                    "conges_par_mois",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        help_text="Code du travail tunisien : un jour par mois de travail effectif.",
                        max_digits=5,
                        verbose_name="jours de congé par mois",
                    ),
                ),
                (
                    "solde_conges_initial",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Jours déjà acquis à la création de la fiche (reprise de l'ancien logiciel).",
                        max_digits=5,
                        verbose_name="solde de congés de départ",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        blank=True,
                        help_text="Compte OptiLink de l'employé, pour qu'il demande ses congés lui-même.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employé",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("annuel", "Congé annuel payé"),
                            ("maladie", "Congé maladie"),
                            ("exceptionnel", "Congé exceptionnel (mariage, décès…)"),
                            ("maternite", "Congé de maternité ou de paternité"),
                            ("sans_solde", "Congé sans solde"),
                        ],
                        max_length=20,
                    ),
                ),
                ("debut", models.DateField(verbose_name="du")),
                ("fin", models.DateField(verbose_name="au")),
                (
                    "jours",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Jours ouvrables, dimanches exclus.",
                        max_digits=5,
                    ),
                ),
                ("motif", models.CharField(blank=True, max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demandee", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="demandee",
                        max_length=10,
                    ),
                ),
                ("decidee_le", models.DateTimeField(blank=True, null=True)),
                ("commentaire_decision", models.CharField(blank=True, max_length=200)),
                (
                    "decidee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demandee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conges",
                        to="rh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de congé",
                "verbose_name_plural": "demandes de congé",
                "ordering": ["-debut"],
                "permissions": [
                    (
                        "decider_demandeconge",
                        "Peut accepter ou refuser une demande de congé",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("retard", "En retard"),
                            ("absent_justifie", "Absent justifié"),
                            ("absent", "Absent non justifié"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "arrivee",
                    models.TimeField(blank=True, null=True, verbose_name="arrivée"),
                ),
                (
                    "depart",
                    models.TimeField(blank=True, null=True, verbose_name="départ"),
                ),
                ("commentaire", models.CharField(blank=True, max_length=200)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pointages",
                        to="rh.employe",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employe", "date"), name="un_pointage_par_jour"
                    )
                ],
            },
        ),
    ]
