# Generated by Django 5.2.17 on 2026-10-03 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0005_societes"),
        ("rh", "0003_droits_des_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="salaire_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Salaire brut mensuel : plafonne les acomptes, sert à la paie.",
                max_digits=12,
                null=True,
                verbose_name="salaire de base",
            ),
        ),
        migrations.CreateModel(
            name="Acompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("montant", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "mois",
                    models.DateField(help_text="Paie qui le retiendra (1er du mois)."),
                ),
                ("motif", models.CharField(blank=True, max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demande", "En attente"),
                            ("accorde", "Accordé, à verser"),
                            ("verse", "Versé"),
                            ("refuse", "Refusé"),
                            ("annule", "Annulé"),
                        ],
                        default="demande",
                        max_length=10,
                    ),
                ),
                ("decide_le", models.DateTimeField(blank=True, null=True)),
                ("commentaire_decision", models.CharField(blank=True, max_length=200)),
                (
                    "mode_versement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("especes", "Espèces"),
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                        ],
                        max_length=10,
                    ),
                ),
                ("verse_le", models.DateField(blank=True, null=True)),
                ("reference_versement", models.CharField(blank=True, max_length=60)),
                (
                    "decide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demande_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acomptes",
                        to="rh.employe",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
                "permissions": [
                    ("decider_acompte", "Peut accorder, refuser et verser un acompte")
                ],
            },
        ),
        migrations.CreateModel(
            name="Prime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rendement", "Prime de rendement"),
                            ("objectif", "Prime d'objectif (ventes)"),
                            ("assiduite", "Prime d'assiduité"),
                            ("fete", "Prime de fête (Aïd…)"),
                            ("exceptionnelle", "Prime exceptionnelle"),
                            ("autre", "Autre prime"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "mois",
                    models.DateField(help_text="Paie qui la versera (1er du mois)."),
                ),
                ("motif", models.CharField(blank=True, max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("proposee", "Proposée"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="proposee",
                        max_length=10,
                    ),
                ),
                ("validee_le", models.DateTimeField(blank=True, null=True)),
                ("commentaire_decision", models.CharField(blank=True, max_length=200)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primes",
                        to="rh.employe",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "proposee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-mois", "-cree_le"],
                "permissions": [("valider_prime", "Peut valider ou refuser une prime")],
            },
        ),
    ]
