# Generated by Django 5.2.17 on 2026-10-01 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("reseau", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("lunettes", "Lunettes"), ("lentilles", "Lentilles")],
                        max_length=10,
                    ),
                ),
                ("date_prescription", models.DateField()),
                (
                    "prescripteur",
                    models.CharField(
                        help_text="Nom de l'ophtalmologiste.", max_length=200
                    ),
                ),
                (
                    "prescripteur_rpps",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$", "Le n° RPPS compte 11 chiffres."
                            )
                        ],
                        verbose_name="n° RPPS",
                    ),
                ),
                ("mesures_chiffrees", models.TextField(editable=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="crm.client",
                    ),
                ),
                (
                    "magasin_saisie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "saisie_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "prescription",
                "ordering": ["-date_prescription", "-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="AccesPrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("saisie", "Saisie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acces",
                        to="optique.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "accès à une prescription",
                "verbose_name_plural": "accès aux prescriptions",
                "ordering": ["-horodatage"],
            },
        ),
    ]
