# Generated by Django 5.2.17 on 2026-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optique", "0003_identifiant_prescripteur"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ophtalmologue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom affiché, par exemple « Dr Ben Salah ».",
                        max_length=200,
                    ),
                ),
                ("cle", models.CharField(editable=False, max_length=200, unique=True)),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone"
                    ),
                ),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ophtalmologiste",
                "ordering": ["nom"],
            },
        ),
    ]
