# Generated by Django 5.2.17 on 2026-10-07 19:37

from django.db import migrations, models


def recalculer_cles(apps, schema_editor):
    """Les mots de la clé sont désormais triés (« nom prénom » = « prénom nom »)."""
    from apps.optique.ophtalmologues import cle_ophtalmologue

    Ophtalmologue = apps.get_model("optique", "Ophtalmologue")
    prises = set(Ophtalmologue.objects.values_list("cle", flat=True))
    for medecin in Ophtalmologue.objects.order_by("pk"):
        cle = cle_ophtalmologue(medecin.nom)
        if cle != medecin.cle and cle not in prises:
            prises.discard(medecin.cle)
            prises.add(cle)
            medecin.cle = cle
            medecin.save(update_fields=["cle"])


class Migration(migrations.Migration):

    dependencies = [
        ("optique", "0004_ophtalmologues"),
    ]

    operations = [
        migrations.AddField(
            model_name="ophtalmologue",
            name="adresse",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ophtalmologue",
            name="anciens_codes",
            field=models.CharField(
                blank=True,
                help_text="CodeMedecin de l'ancien logiciel, séparés par des virgules s'il y avait des doublons regroupés ici.",
                max_length=200,
                verbose_name="codes dans l'ancien logiciel",
            ),
        ),
        migrations.AddField(
            model_name="ophtalmologue",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AddField(
            model_name="ophtalmologue",
            name="telephone_2",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="téléphone 2"
            ),
        ),
        migrations.RunPython(recalculer_cles, migrations.RunPython.noop),
    ]
