# Generated by Django 5.2.17 on 2026-10-07 19:54

from django.db import migrations, models


def numeroter(apps, schema_editor):
    """Médecins déjà dans la liste : 001, 002… dans l'ordre d'ajout."""
    Ophtalmologue = apps.get_model("optique", "Ophtalmologue")
    for rang, medecin in enumerate(Ophtalmologue.objects.order_by("pk"), start=1):
        medecin.code = f"{rang:03d}"
        medecin.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ("optique", "0005_ophtalmologues_coordonnees"),
    ]

    operations = [
        migrations.AddField(
            model_name="ophtalmologue",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Code du médecin : 001, 002…",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(numeroter, migrations.RunPython.noop),
    ]
