# Generated by Django 5.2.17 on 2026-09-30 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvenementSecurite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("connexion_reussie", "Connexion réussie"),
                            ("connexion_echouee", "Connexion échouée"),
                            ("deconnexion", "Déconnexion"),
                            ("mfa_reussie", "Code MFA accepté"),
                            ("mfa_echouee", "Code MFA refusé"),
                            ("mfa_activee", "MFA activée"),
                            ("compte_desactive", "Compte désactivé pour inactivité"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant saisi, conservé même sans compte.",
                        max_length=150,
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agent_utilisateur", models.CharField(blank=True, max_length=255)),
                ("details", models.CharField(blank=True, max_length=255)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "événement de sécurité",
                "verbose_name_plural": "événements de sécurité",
                "ordering": ["-horodatage"],
            },
        ),
    ]
