# Generated by Django 5.2.17 on 2026-10-06 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_CORBEILLE, ajouter_aux_roles_existants
from core import rls

# Un élément sans magasin (pays, profil…) est visible de tous ; les droits font le reste.
CONDITION = "magasin_id IS NULL OR optilink_magasin_visible(magasin_id)"


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.activer("securite_elementcorbeille", CONDITION))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.desactiver("securite_elementcorbeille"))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_CORBEILLE)


class Migration(migrations.Migration):

    dependencies = [
        ("securite", "0005_profils"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementCorbeille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("type_libelle", models.CharField(max_length=150, verbose_name="type")),
                ("objet_pk", models.CharField(max_length=64)),
                ("libelle", models.CharField(max_length=255, verbose_name="élément")),
                ("magasin_id", models.BigIntegerField(blank=True, null=True)),
                ("nombre_objets", models.PositiveIntegerField(default=1)),
                ("donnees", models.JSONField()),
                ("supprime_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expire_le", models.DateTimeField(db_index=True)),
                (
                    "supprime_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "élément de la corbeille",
                "verbose_name_plural": "corbeille",
                "ordering": ["-supprime_le"],
                "permissions": [
                    (
                        "restaurer_elementcorbeille",
                        "Restaurer un élément de la corbeille",
                    )
                ],
            },
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
