# Generated by Django 5.2.17 on 2026-10-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0017_add_actor_email"),
        ("securite", "0005_profils"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModificationDroits",
            fields=[],
            options={
                "verbose_name": "modification des droits",
                "verbose_name_plural": "modifications des droits",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auditlog.logentry",),
        ),
        migrations.AlterField(
            model_name="evenementsecurite",
            name="type",
            field=models.CharField(
                choices=[
                    ("connexion_reussie", "Connexion réussie"),
                    ("connexion_echouee", "Connexion échouée"),
                    ("deconnexion", "Déconnexion"),
                    ("mfa_reussie", "Code MFA accepté"),
                    ("mfa_echouee", "Code MFA refusé"),
                    ("mfa_activee", "MFA activée"),
                    ("compte_desactive", "Compte désactivé pour inactivité"),
                    ("mfa_reinitialisee", "MFA réinitialisée par un administrateur"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
