# Generated by Django 5.2.17 on 2026-09-30 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "région",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Magasin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(blank=True, max_length=200)),
                ("code_postal", models.CharField(blank=True, max_length=10)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="magasins",
                        to="reseau.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "magasin",
                "ordering": ["code"],
            },
        ),
    ]
