# Generated by Django 5.2.17 on 2026-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0002_pays"),
    ]

    operations = [
        migrations.AddField(
            model_name="magasin",
            name="nombre_peniches",
            field=models.PositiveSmallIntegerField(
                default=200,
                help_text="Bacs numérotés de 1 à ce nombre où l'on range l'équipement d'une commande.",
                verbose_name="nombre de péniches",
            ),
        ),
    ]
