# Generated by Django 5.2.17 on 2026-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0005_societes"),
    ]

    operations = [
        migrations.AddField(
            model_name="magasin",
            name="type",
            field=models.CharField(
                choices=[("magasin", "Magasin"), ("depot", "Dépôt central")],
                default="magasin",
                help_text="Dépôt central : la marchandise des fournisseurs y est reçue et contrôlée (BL, factures achat, bons retour), puis envoyée aux magasins par transfert.",
                max_length=10,
            ),
        ),
    ]
