# Generated by Django 5.2.17 on 2026-10-06 21:58

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_VILLES, ajouter_aux_roles_existants

# Villes de départ en Tunisie (liste de l'ancien logiciel, orthographe corrigée).
VILLES_TN = [
    "Aïn Zaghouan", "Ariana", "Béja", "Ben Arous", "Bizerte", "Den Den", "Djerba",
    "El Ghazala", "El Menzah", "El Menzah 6", "El Mourouj", "El Mourouj 1", "El Wahat",
    "Ennasr", "Ezzouhour", "Gabès", "Gafsa", "Hammam Lif", "Hammamet", "Jardins de Carthage",
    "Kairouan", "Kasserine", "Kébili", "Kélibia", "L'Aouina", "La Manouba", "La Marsa",
    "La Soukra", "Le Bardo", "Le Kef", "Le Kram", "Mahdia", "Médenine", "Mnihla", "Monastir",
    "Nabeul", "Sfax", "Sidi Bouzid", "Sidi Daoud", "Siliana", "Sousse", "Tozeur", "Tunis",
    "Zaghouan",
]


def remplir(apps, schema_editor):
    Pays = apps.get_model("reseau", "Pays")
    Ville = apps.get_model("reseau", "Ville")
    tunisie = Pays.objects.filter(code="TN").first()
    if tunisie is not None:
        Ville.objects.bulk_create([Ville(pays=tunisie, nom=nom) for nom in VILLES_TN])


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, {"Administrateur": PERMISSIONS_VILLES})


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0006_magasin_type"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "est_active",
                    models.BooleanField(
                        default=True,
                        help_text="Une ville désactivée n'est plus proposée.",
                        verbose_name="active",
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="villes",
                        to="reseau.pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "ville",
                "ordering": ["nom"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nom"),
                        models.F("pays"),
                        name="ville_unique_par_pays",
                    )
                ],
            },
        ),
        migrations.RunPython(remplir, migrations.RunPython.noop),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
