# Generated by Django 5.2.17 on 2026-10-06 22:23

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_BANQUES, ajouter_aux_roles_existants

# Banques de Tunisie données par Anas le 2026-10-06 (code banque du RIB sur 2 chiffres).
BANQUES_TN = [
    ("00", "BANQUE CENTRALE DE TUNISIE", "BCT"),
    ("01", "ARAB TUNISIAN BANK", "ATB"),
    ("02", "BANQUE FRANCO-TUNISIENNE", "BFT"),
    ("03", "BANQUE NATIONALE AGRICOLE", "BNA"),
    ("04", "ATTIJARI BANK", "BS"),
    ("05", "BANQUE DE TUNISIE", "BT"),
    ("07", "AMEN BANK", "AB"),
    ("08", "BANQUE INTERNATIONALE ARABE DE TUNISIE", "BIAT"),
    ("10", "SOCIETE TUNISIENNE DE BANQUE", "STB"),
    ("11", "UNION BANCAIRE POUR LE COMMERCE ET L'INDUSTRIE", "UBCI"),
    ("12", "UNION INTERNATIONALE DE BANQUES", "UIB"),
    ("14", "BANQUE DE L'HABITAT", "BH"),
    ("17", "CENTRE DES CHEQUES POSTAUX", "CCP"),
    ("20", "BANQUE TUNISO-KOWEITIENNE", "BTK"),
    ("23", "QATAR NATIONAL BANK", "QNB"),
    ("25", "BANQUE ZITOUNA", "BZ"),
    ("26", "BANQUE ARABE TUNISO-LIBYENNE", "BTL"),
    ("27", "BANQUE TUNISIENNE DE SOLIDARITE", "BTS"),
    ("32", "EL BARAKA BANK", "BEST"),
    ("47", "WIFAK INTERNATIONAL BANK", "WIB"),
]


def remplir(apps, schema_editor):
    Pays = apps.get_model("reseau", "Pays")
    Banque = apps.get_model("reseau", "Banque")
    tunisie = Pays.objects.filter(code="TN").first()
    if tunisie is not None:
        Banque.objects.bulk_create(
            [Banque(pays=tunisie, code=c, nom=n, sigle=s) for c, n, s in BANQUES_TN]
        )


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, {"Administrateur": PERMISSIONS_BANQUES})


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0007_villes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code de la banque dans le RIB, ex. 08.", max_length=5
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("sigle", models.CharField(blank=True, max_length=20)),
                (
                    "est_active",
                    models.BooleanField(
                        default=True,
                        help_text="Une banque désactivée n'est plus proposée.",
                        verbose_name="active",
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="banques",
                        to="reseau.pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "banque",
                "ordering": ["nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pays", "code"), name="banque_code_unique_par_pays"
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nom"),
                        models.F("pays"),
                        name="banque_unique_par_pays",
                    ),
                ],
            },
        ),
        migrations.RunPython(remplir, migrations.RunPython.noop),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
