# Generated by Django 5.2.17 on 2026-10-10 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


def creer_les_depots(apps, schema_editor):
    """Chaque magasin reçoit son dépôt : de vente, ou central pour l'ancien « dépôt central »."""
    Magasin = apps.get_model("reseau", "Magasin")
    Depot = apps.get_model("reseau", "Depot")
    for magasin in Magasin.objects.all():
        central = magasin.type == "depot"
        Depot.objects.create(
            magasin=magasin,
            code=magasin.code,
            nom=magasin.nom if central else f"Dépôt {magasin.nom}"[:100],
            type="central" if central else "vente",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("reseau", "0008_banques"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Ex. DEPTN, DEPCEN, DEPCAS.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vente", "Dépôt de vente"),
                            ("central", "Dépôt central"),
                            ("casse", "Dépôt casse"),
                        ],
                        default="vente",
                        max_length=10,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depots",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "dépôt",
                "ordering": ["magasin__code", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("type", "vente")),
                        fields=("magasin",),
                        name="un_depot_de_vente_par_magasin",
                    )
                ],
            },
        ),
        migrations.RunPython(creer_les_depots, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="magasin",
            name="type",
        ),
    ]
