# Generated by Django 5.2.17 on 2026-10-10 20:53

from django.db import migrations, models


def reprendre_les_coordonnees(apps, schema_editor):
    """Les dépôts déjà créés reprennent l'adresse, la ville et le téléphone de leur magasin."""
    Depot = apps.get_model("reseau", "Depot")
    for depot in Depot.objects.select_related("magasin"):
        depot.adresse = depot.magasin.adresse
        depot.ville = depot.magasin.ville
        depot.telephone = depot.magasin.telephone
        depot.save(update_fields=["adresse", "ville", "telephone"])


class Migration(migrations.Migration):

    dependencies = [
        ("reseau", "0009_depots"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="adresse",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="depot",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, verbose_name="téléphone"),
        ),
        migrations.AddField(
            model_name="depot",
            name="ville",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="depot",
            name="code",
            field=models.CharField(
                help_text="Ex. DEPTN, DEPCEN, DEPCAS.",
                max_length=20,
                unique=True,
                verbose_name="code dépôt",
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="libellé"),
        ),
        migrations.RunPython(reprendre_les_coordonnees, migrations.RunPython.noop),
    ]
