# Generated by Django 5.2.17 on 2026-10-01 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reseau", "0002_pays"),
        ("stock", "0004_article_sur_commande"),
        ("ventes", "0011_type_commande_fournisseur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("adresse", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "fournisseur",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="CommandeFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True,
                        help_text="N° donné par le fournisseur.",
                        max_length=60,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoyee", "Envoyée"),
                            ("recue", "Reçue"),
                            ("annulee", "Annulée"),
                        ],
                        default="envoyee",
                        max_length=10,
                    ),
                ),
                ("recue_le", models.DateTimeField(blank=True, null=True)),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
                (
                    "passee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="achats.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "commande fournisseur",
                "verbose_name_plural": "commandes fournisseurs",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommandeFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="Œil, correction, traitement… pour le fournisseur.",
                        max_length=300,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="achats.commandefournisseur",
                    ),
                ),
                (
                    "ligne_vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_fournisseur",
                        to="ventes.lignevente",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de commande fournisseur",
            },
        ),
        migrations.AddConstraint(
            model_name="commandefournisseur",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"),
                name="commande_fournisseur_sans_doublon",
            ),
        ),
    ]
