# Generated by Django 5.2.17 on 2026-10-04 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_CASSES, ajouter_aux_roles_existants
from core import rls


# Les casses suivent leur vente (la sous-requête est elle-même filtrée).
CONDITION = "EXISTS (SELECT 1 FROM ventes_vente v WHERE v.id = vente_id)"


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.activer("achats_casseverre", CONDITION))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(rls.desactiver("achats_casseverre"))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_CASSES)


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0003_droits_des_roles"),
        ("ventes", "0016_prises_en_charge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CasseVerre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("atelier", "Casse à l'atelier (montage)"),
                            ("fournisseur", "Défaut du fournisseur"),
                            ("client", "Casse par le client"),
                        ],
                        max_length=12,
                    ),
                ),
                ("observation", models.CharField(blank=True, max_length=300)),
                (
                    "declaree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ligne_commande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casse",
                        to="achats.lignecommandefournisseur",
                        verbose_name="verre commandé",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casses_verres",
                        to="ventes.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "casse de verre",
                "verbose_name_plural": "casses de verres",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
