# Generated by Django 5.2.17 on 2026-10-05 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_RECEPTIONS, ajouter_aux_roles_existants
from core import rls

# Les bons suivent leur magasin ; les lignes suivent leur bon (sous-requête elle-même filtrée).
TABLES = {
    "achats_bonreception": "optilink_magasin_visible(magasin_id)",
    "achats_lignereception": "EXISTS (SELECT 1 FROM achats_bonreception b WHERE b.id = bon_id)",
}


def numeroter_fournisseurs(apps, schema_editor):
    """Les fournisseurs déjà saisis reçoivent un code 1, 2, 3… dans leur ordre de création."""
    Fournisseur = apps.get_model("achats", "Fournisseur")
    for code, fournisseur in enumerate(Fournisseur.objects.order_by("cree_le", "pk"), start=1):
        fournisseur.code = code
        fournisseur.save(update_fields=["code"])


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_RECEPTIONS)


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0004_casses_verres"),
        ("reseau", "0005_societes"),
        ("stock", "0008_famille_supplement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="assujetti",
            field=models.BooleanField(default=True, verbose_name="assujetti à la TVA"),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="banque",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="capital_social",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="code",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Numéro attribué à la création : 1, 2, 3…",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="code_douane",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="code_postal",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="exoneration_au",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="exoneration_du",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="fax",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="fodec",
            field=models.BooleanField(
                default=False,
                help_text="Ajoute 1 % du montant net HT, soumis à la TVA.",
                verbose_name="FODEC",
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="forme_juridique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SARL", "SARL"),
                    ("SUARL", "SUARL"),
                    ("SA", "SA"),
                    ("SNC", "SNC"),
                    ("PP", "Personne physique"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="fournisseur_verres",
            field=models.BooleanField(
                default=False,
                help_text="Laboratoire : verres commandés.",
                verbose_name="fournisseur de verres",
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="matricule_fiscal",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="notre_code",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="notre code chez le fournisseur"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="numero_exoneration",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="n° d'exonération"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="observation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="regime_tva",
            field=models.CharField(
                choices=[
                    ("assujetti", "Payer la TVA"),
                    ("export", "Export"),
                    ("exoneration", "Exonération"),
                ],
                default="assujetti",
                max_length=12,
                verbose_name="régime de TVA",
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="registre_commerce",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="registre de commerce"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="responsable",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="rib",
            field=models.CharField(blank=True, max_length=34, verbose_name="RIB"),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="site_web",
            field=models.URLField(blank=True, verbose_name="site web"),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="telephone_2",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="téléphone 2"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="timbre_fiscal",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="ville",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="nom",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="raison sociale"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="telephone",
            field=models.CharField(blank=True, max_length=30, verbose_name="téléphone"),
        ),
        migrations.CreateModel(
            name="BonReception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("date_saisie", models.DateField(verbose_name="date de saisie")),
                (
                    "numero_bl",
                    models.CharField(max_length=60, verbose_name="n° BL fournisseur"),
                ),
                ("date_bl", models.DateField(verbose_name="date BL fournisseur")),
                ("observation", models.TextField(blank=True)),
                (
                    "taux_remise_ex",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="remise exceptionnelle (%)",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("non_facture", "Non facturé"),
                            ("facture", "Facturé"),
                        ],
                        default="non_facture",
                        max_length=12,
                    ),
                ),
                (
                    "numero_facture",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="n° facture fournisseur"
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_remise",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "remise_ex",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_net_ht",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_fodec",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_tva",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_ttc",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions",
                        to="achats.fournisseur",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "bon de réception",
                "verbose_name_plural": "bons de réception",
                "ordering": ["-annee", "-sequence"],
            },
        ),
        migrations.CreateModel(
            name="LigneReception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oeil",
                    models.CharField(
                        blank=True,
                        choices=[("D", "Œil droit"), ("G", "Œil gauche")],
                        max_length=1,
                        verbose_name="œil",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=300, verbose_name="désignation"),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="quantité")),
                (
                    "prix_achat_ht",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="prix d'achat HT"
                    ),
                ),
                (
                    "taux_remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("taux_tva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("net_ht", models.DecimalField(decimal_places=3, max_digits=14)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=14)),
                ("non_conforme", models.BooleanField(default=False)),
                ("motif", models.CharField(blank=True, max_length=200)),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="n° de série"
                    ),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="n° de lot"
                    ),
                ),
                ("date_peremption", models.DateField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "bon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="achats.bonreception",
                    ),
                ),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verre commandé pour un client.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions",
                        to="achats.lignecommandefournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de réception",
                "verbose_name_plural": "lignes de réception",
            },
        ),
        migrations.AddConstraint(
            model_name="bonreception",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"),
                name="bon_reception_sans_doublon",
            ),
        ),
        migrations.AddConstraint(
            model_name="bonreception",
            constraint=models.UniqueConstraint(
                fields=("fournisseur", "numero_bl"), name="bl_fournisseur_une_fois"
            ),
        ),
        migrations.RunPython(numeroter_fournisseurs, migrations.RunPython.noop),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
