# Generated by Django 5.2.17 on 2026-10-05 15:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_FACTURES_ACHAT, ajouter_aux_roles_existants
from core import rls

TABLES = {"achats_factureachat": "optilink_magasin_visible(magasin_id)"}


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_FACTURES_ACHAT)


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0005_bons_reception"),
        ("reseau", "0005_societes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactureAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("date_entree", models.DateField(verbose_name="date d'entrée")),
                (
                    "reference_fournisseur",
                    models.CharField(
                        help_text="N° de la facture chez le fournisseur.",
                        max_length=60,
                        verbose_name="référence fournisseur",
                    ),
                ),
                (
                    "date_reference",
                    models.DateField(verbose_name="date de la facture fournisseur"),
                ),
                (
                    "taux_remise_ex",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="remise exceptionnelle (%)",
                    ),
                ),
                (
                    "frais_supplementaires",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Transport, port… (TTC).",
                        max_digits=14,
                    ),
                ),
                (
                    "timbre_fiscal",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "ajustement",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Écart d'arrondi pour retrouver le total TTC de la facture papier.",
                        max_digits=10,
                        verbose_name="ajustement des totaux",
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "paiement",
                    models.CharField(
                        choices=[
                            ("non_paye", "Non payé"),
                            ("partiel", "Payé en partie"),
                            ("paye", "Payé"),
                        ],
                        default="non_paye",
                        max_length=10,
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_remise",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "remise_ex",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_net_ht",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_fodec",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_tva",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_ttc",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures_achat",
                        to="achats.fournisseur",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "facture achat",
                "verbose_name_plural": "factures achat",
                "ordering": ["-annee", "-sequence"],
            },
        ),
        migrations.AddField(
            model_name="bonreception",
            name="facture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bons",
                to="achats.factureachat",
                verbose_name="facture achat",
            ),
        ),
        migrations.AddConstraint(
            model_name="factureachat",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"),
                name="facture_achat_sans_doublon",
            ),
        ),
        migrations.AddConstraint(
            model_name="factureachat",
            constraint=models.UniqueConstraint(
                fields=("fournisseur", "reference_fournisseur"),
                name="facture_fournisseur_une_fois",
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
]
