# Generated by Django 5.2.17 on 2026-10-05 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_BONS_RETOUR, ajouter_aux_roles_existants
from core import rls

TABLES = {
    "achats_bonretour": "optilink_magasin_visible(magasin_id)",
    "achats_ligneretour": "EXISTS (SELECT 1 FROM achats_bonretour b WHERE b.id = bon_id)",
}
PERMS = PERMISSIONS_BONS_RETOUR


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMS)



class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0006_factures_achat"),
        ("reseau", "0006_magasin_type"),
        ("stock", "0010_alter_mouvementstock_type_transfertstock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonRetour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("date_retour", models.DateField(verbose_name="date du retour")),
                ("motif", models.CharField(blank=True, max_length=200)),
                ("observation", models.TextField(blank=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("non_facture", "Non déduit"),
                            ("facture", "Déduit d'une facture"),
                        ],
                        default="non_facture",
                        max_length=12,
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_remise",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "remise_ex",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_net_ht",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_fodec",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_tva",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_ttc",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retours",
                        to="achats.factureachat",
                        verbose_name="facture achat",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retours",
                        to="achats.fournisseur",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "bon retour fournisseur",
                "verbose_name_plural": "bons retour fournisseur",
                "ordering": ["-annee", "-sequence"],
            },
        ),
        migrations.CreateModel(
            name="LigneRetour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=300, verbose_name="désignation"),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="quantité")),
                (
                    "prix_achat_ht",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="prix d'achat HT"
                    ),
                ),
                (
                    "taux_remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("taux_tva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("net_ht", models.DecimalField(decimal_places=3, max_digits=14)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=14)),
                ("motif", models.CharField(blank=True, max_length=200)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.article",
                    ),
                ),
                (
                    "bon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="achats.bonretour",
                    ),
                ),
                (
                    "ligne_reception",
                    models.OneToOneField(
                        blank=True,
                        help_text="Ligne non conforme du bon de réception renvoyée.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retour",
                        to="achats.lignereception",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de retour",
                "verbose_name_plural": "lignes de retour",
            },
        ),
        migrations.AddConstraint(
            model_name="bonretour",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"), name="bon_retour_sans_doublon"
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
