# Generated by Django 5.2.17 on 2026-10-09 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.securite.roles import PERMISSIONS_REGLEMENTS_FOURNISSEURS, ajouter_aux_roles_existants
from core import rls

TABLES = {
    "achats_reglementfournisseur": "optilink_magasin_visible(magasin_id)",
    "achats_imputationreglement": (
        "EXISTS (SELECT 1 FROM achats_reglementfournisseur r WHERE r.id = reglement_id)"
    ),
}


def cloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table, condition in TABLES.items():
            schema_editor.execute(rls.activer(table, condition))


def decloisonner(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for table in TABLES:
            schema_editor.execute(rls.desactiver(table))


def ajouter_droits(apps, schema_editor):
    ajouter_aux_roles_existants(apps, PERMISSIONS_REGLEMENTS_FOURNISSEURS)


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0007_bonretour_ligneretour_and_more"),
        ("reseau", "0008_banques"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglementFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(max_length=40, unique=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("date_reglement", models.DateField(verbose_name="date du règlement")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("traite", "Traite"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="N° du chèque, de la traite ou du virement.",
                        max_length=60,
                    ),
                ),
                ("banque", models.CharField(blank=True, max_length=100)),
                (
                    "echeance",
                    models.DateField(blank=True, null=True, verbose_name="échéance"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("a_echoir", "À échoir"), ("debite", "Débité")],
                        default="debite",
                        max_length=10,
                    ),
                ),
                ("debite_le", models.DateField(blank=True, null=True)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="montant versé"
                    ),
                ),
                (
                    "taux_retenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="taux de retenue à la source (%)",
                    ),
                ),
                (
                    "retenue",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="retenue à la source",
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglements",
                        to="achats.fournisseur",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "règlement fournisseur",
                "verbose_name_plural": "règlements fournisseurs",
                "ordering": ["-date_reglement", "-sequence"],
            },
        ),
        migrations.CreateModel(
            name="ImputationReglement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=3, max_digits=14)),
                ("le", models.DateField()),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imputations",
                        to="achats.factureachat",
                    ),
                ),
                (
                    "reglement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imputations",
                        to="achats.reglementfournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "imputation de règlement",
                "verbose_name_plural": "imputations de règlement",
            },
        ),
        migrations.AddConstraint(
            model_name="reglementfournisseur",
            constraint=models.UniqueConstraint(
                fields=("magasin", "annee", "sequence"),
                name="reglement_fournisseur_sans_doublon",
            ),
        ),
        migrations.RunPython(cloisonner, decloisonner),
        migrations.RunPython(ajouter_droits, migrations.RunPython.noop),
    ]
