# Generated by Django 5.2.17 on 2026-10-10 20:13

import django.db.models.deletion
from django.db import migrations, models


def _depot_de(apps):
    """{magasin_id: dépôt_id} : à la migration, chaque magasin a un seul dépôt."""
    Depot = apps.get_model("reseau", "Depot")
    depots = {}
    for depot in Depot.objects.order_by("-type", "code"):  # « vente » avant « central »
        depots.setdefault(depot.magasin_id, depot.pk)
    return depots


def remplir(apps, schema_editor):
    Bon = apps.get_model("achats", "BonReception")
    for magasin_id, depot_id in _depot_de(apps).items():
        Bon.objects.filter(magasin_id=magasin_id).update(depot_id=depot_id)


class Migration(migrations.Migration):
    dependencies = [
        ("achats", "0008_reglements_fournisseurs"),
        ("reseau", "0009_depots"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonreception",
            name="depot",
            field=models.ForeignKey(
                help_text="Dépôt où les articles de stock sont entrés.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
        migrations.RunPython(remplir, migrations.RunPython.noop),
    ]
