# Generated by Django 5.2.17 on 2026-10-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achats", "0009_depots"),
        ("reseau", "0009_depots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonreception",
            name="depot",
            field=models.ForeignKey(
                help_text="Dépôt où les articles de stock sont entrés.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reseau.depot",
                verbose_name="dépôt",
            ),
        ),
    ]
