# Generated by Django 5.2.17 on 2026-10-01 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reseau", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "civilite",
                    models.CharField(
                        blank=True, choices=[("mme", "Mme"), ("m", "M.")], max_length=3
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "telephone",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("adresse", models.CharField(blank=True, max_length=200)),
                ("code_postal", models.CharField(blank=True, max_length=10)),
                ("ville", models.CharField(blank=True, max_length=100)),
                (
                    "accepte_relances",
                    models.BooleanField(
                        default=False,
                        help_text="Consentement aux relances par e-mail ou SMS (RGPD).",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "magasin_origine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "ordering": ["nom", "prenom"],
                "indexes": [
                    models.Index(
                        fields=["nom", "prenom"], name="crm_client_nom_25f9af_idx"
                    )
                ],
            },
        ),
    ]
