# Generated by Django 5.2.17 on 2026-10-02 14:46

from django.db import migrations, models


def societe_des_clients_professionnels(apps, schema_editor):
    # Avant ce champ, une entreprise cliente était saisie dans nom et prénom.
    Client = apps.get_model("crm", "Client")
    for client in Client.objects.exclude(matricule_fiscal="").filter(societe=""):
        client.societe = f"{client.nom} {client.prenom}".strip()
        client.save(update_fields=["societe"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_matricule_fiscal"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="societe",
            field=models.CharField(
                blank=True,
                help_text="Client professionnel : raison sociale, au nom de laquelle on facture.",
                max_length=200,
                verbose_name="société",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="telephone_2",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, verbose_name="téléphone 2"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="matricule_fiscal",
            field=models.CharField(
                blank=True,
                help_text="Client professionnel : identifiant fiscal sur la facture.",
                max_length=30,
            ),
        ),
        migrations.RunPython(societe_des_clients_professionnels, migrations.RunPython.noop),
    ]
