# Generated by Django 5.2.17 on 2026-10-04 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


def creer_cnam(apps, schema_editor):
    """La CNAM tunisienne existe d'office ; assurances et mutuelles se créent dans l'administration."""
    Pays = apps.get_model("reseau", "Pays")
    Organisme = apps.get_model("crm", "Organisme")
    tunisie = Pays.objects.filter(code="TN").first()
    if tunisie is not None:
        Organisme.objects.get_or_create(
            pays=tunisie, nom="CNAM", defaults={"type": "caisse", "est_actif": True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_numero_fiche"),
        ("reseau", "0005_societes"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="numero_affilie",
            field=models.CharField(
                blank=True,
                help_text="N° d'assuré ou d'adhérent.",
                max_length=40,
                verbose_name="n° d'affilié",
            ),
        ),
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("caisse", "Caisse d'assurance maladie"),
                            ("assurance", "Assurance"),
                            ("mutuelle", "Mutuelle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reseau.pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisme de prise en charge",
                "verbose_name_plural": "organismes de prise en charge",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="organisme",
            field=models.ForeignKey(
                blank=True,
                help_text="CNAM, assurance ou mutuelle du client (PEC client).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="crm.organisme",
                verbose_name="prise en charge",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisme",
            constraint=models.UniqueConstraint(
                fields=("pays", "nom"), name="organisme_unique_par_pays"
            ),
        ),
        migrations.RunPython(creer_cnam, migrations.RunPython.noop),
    ]
