# Generated by Django 5.2.17 on 2026-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_numero_fiche"),
        ("reseau", "0005_societes"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="reference_externe",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="N° de la fiche dans l'ancien logiciel, conservé à l'import des clients.",
                max_length=60,
                verbose_name="ancien n° de fiche",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_externe", ""), _negated=True),
                fields=("reference_externe",),
                name="client_reference_externe_unique",
            ),
        ),
    ]
