# Generated by Django 5.2.17 on 2026-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_ancien_numero_fiche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisme",
            name="type",
            field=models.CharField(
                choices=[
                    ("caisse", "Caisse d'assurance maladie"),
                    ("assurance", "Assurance"),
                    ("mutuelle", "Mutuelle"),
                    ("convention", "Convention (entreprise, association)"),
                ],
                max_length=10,
            ),
        ),
    ]
