# Generated by Django 5.2.17 on 2026-10-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_organisme_convention"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="liste_noire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="liste_noire_le",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="motif_liste_noire",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="motif de la liste noire"
            ),
        ),
    ]
